### ISSUE TITLE
Question about changing Host CPU 

### ISSUE THREAD

**Issue by killmasta93** [diegogslomp/samba-ad-dc#16]
Hi @diegogslomp Hope all is well,
Currently im migrating another docker container to another host the issue is that on the current host i have a different CPU while on the other host i have KVM when i migrate i see the logs 

```
samba: /lib/x86_64-linux-gnu/libjansson.so.4: no version information available (required by /usr/local/samba/lib/private/libcommon-auth-samba4.so)

samba: CPU ISA level is lower than required

```
i tried creating another container in the KVM host then copy the private lib and libexec to that container but no luck 

Thank yu=ou

**Comment by diegogslomp** [comment]
Hello

Can you create a fresh domain in the KVM? 

According with [this](https://centosfaq.org/centos/c9s-cpu-isa-level-lower-than-required/) may be something with the CPU model that is configured, I don't use KVM so can't tell. Please let me know if you have any progress.

**Comment by killmasta93** [comment]
Hi @diegogslomp , Correct i created another fresh DC docker on another VM how would i transfer the files? or which folders contains the samba info? to maybe try to migrate 
Thank you

**Comment by diegogslomp** [comment]
Try the rsync that you did [here](https://github.com/diegogslomp/samba-ad-dc/issues/15#issuecomment-1661489304) and update the interface inside smb.conf file.

**Comment by killmasta93** [comment]
hi @diegogslomp thank you so much for the reply it seems in the host that is working it has these folders

`bin  bind-dns  etc  include  lib  libexec  private  sbin  share  var`

while on the host that has the CPU differnt it has these folders
`
bin  bind-dns  etc  include  lib  lib64  libexec   private    sbin  share  shares  var`

it seems that it created the lib64 folder 

i ran the setups 

created docker on the host i want to be migrated then stop the container

then rsync from the old host folder samba to the new host 

and restart the container and same issue with the CPU

**Comment by diegogslomp** [comment]
Hello


Try to rsync only the `etc, private, var` folders from `/usr/local/samba`. If it fails you can


1. Join the old dc and sync the new one if you have connection between them, like the dc2,3,4 from the [docker-compose.yml](https://github.com/diegogslomp/samba-ad-dc/blob/master/docker-compose.yml)


2. Another alternative is to create a `samba-tool domain backup` file and restore to the new one, but in this case the name of the new one should be different from the old one, more info [here](https://wiki.samba.org/index.php/Back_up_and_Restoring_a_Samba_AD_DC)


Let me know if you have any progress
