### ISSUE TITLE
Bind volume

### ISSUE THREAD

**Issue by xgonc** [diegogslomp/samba-ad-dc#17]
Hello,

I'd like to bind mount the directories where samba stores its data. This is more convenient when upgrading samba or upgrading the container.

What directories shall I bind mount? Is `/usr/local/samba/var` enough?

Thanks.

**Comment by diegogslomp** [comment]
Hello

You can create a volume to store the  `/usr/local/samba` dir as the README suggest, if you bind mount on top of a filesystem,  the content already in the dir will not be showed. Any trouble let me know.
