### ISSUE TITLE
Question about samba test?

### ISSUE THREAD

**Issue by killmasta93** [diegogslomp/samba-ad-dc#23]
HI
Currently when i try samba test im getting this not sure if should be alarmed?
this is on one container that i did not changed the default password from the docker-compose
```
ldapsearch -xLLL -b "cn=administrator,cn=users,dc=test,dc=local" -D "cn=administrator,cn=users,dc=test,dc=local"
ldap_bind: Invalid credentials (49)
	additional info: 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1

```

and on another container when i run 
`
 docker exec dcxx samba-tests`

```
# DC4: smbclient //localhost/netlogon -UAdministrator -c "ls"
Password for [DOMAIN\Administrator]:
session setup failed: NT_STATUS_LOGON_FAILURE


```
thanks

**Comment by diegogslomp** [comment]
Hello
The ADMIN_PASS env var inside the docker compose file is used to check the admin in the tests, if the other dcs don't show this warning then is something wrong there. Any trouble please let me know.

**Comment by killmasta93** [comment]
thank you so much
