### ISSUE TITLE
enable CI build and push to dockerhub?

### ISSUE THREAD

**Issue by aspfate** [diegogslomp/samba-ad-dc#27]
enable this CI auto build and push to registry when a new samba version release?
this repo last update at 2 months ago, the latest ci trigered at 8 mouths ago, dockerhub update at 1 days ago. this is not ideal situation.
thanks.

**Comment by diegogslomp** [comment]
Hello
This build is based on the intermediate-stage branch, as I upload to dockerhub manually these days this information will be outdated. When I have some time I'll automate the upload, I need to learn how to do that too. Any trouble let me know
