### ISSUE TITLE
question about DNS

### ISSUE THREAD

**Issue by SimonMcN** [diegogslomp/samba-ad-dc#3]
Please can you tell me why there is a Bind branch ?  What issue does this solve please ?  Is it just extra functionality ? 

TIA

**Comment by diegogslomp** [comment]
Hello!

In this branch I'm testing BIND9 as DNS Backend instead the default SAMBA_INTERNAL, this backend is recommended for complex DNS setups, more details at https://wiki.samba.org/index.php/BIND9_DLZ_DNS_Back_End. For now I recommend that you just use the default backend that works great! Any trouble please let me know.
