### ISSUE TITLE
For information (running virtualised with CPU type QEMU64 or KVM64)

### ISSUE THREAD

**Issue by SimonMcN** [diegogslomp/samba-ad-dc#5]
Just for info, I don't know if you want to put in the documentation but almalinux and rocky Linux won't compile or run on QEMU64 or KVM64  (Fatal glibc error: CPU does not support x86-64-v2) .  The work around is to use the other containers or use HOST emulation.

This is the case during both container creation and when they are running.

Cheers
Simon

**Comment by diegogslomp** [comment]
Thank you Simon for the info! I don't use kvm or qemu to compile, but this info will be here for other users. Since there is nothing that can be done at the repo itself, I'll close this issue. Any trouble please let me know.
